### ISSUE TITLE
ldap passwords are logged 

### ISSUE THREAD

**Issue by timw077** [chef-cookbooks/sssd_ldap#27]
### Cookbook version
Using sssd_ldap (4.1.0)

### Chef-client version
Chef: 12.17.44

### Platform Details
redhat 7.3

### Scenario:
the LDAP authtoken is being displayed in the log.  It should not be, 
```
  * template[/etc/sssd/sssd.conf] action create
    - update content in file /etc/sssd/sssd.conf from bf7d6f to 96711b
    --- /etc/sssd/sssd.conf	2017-02-07 20:35:20.297596442 +0000
    +++ /etc/sssd/.chef-sssd20170209-3060-100rjlw.conf	2017-02-09 16:25:16.698611730 +0000
    @@ -31,7 +31,7 @@
     ldap_tls_reqcert = never
     ldap_tls_cacert = /etc/pki/tls/certs/ca-bundle.crt
     ldap_default_bind_dn = bind_user@example.com
    -ldap_default_authtok = old_password
    +ldap_default_authtok = new_password
     access_provider = ldap
     ldap_access_filter = memberOf=CN=staff,OU=service,DC=example,DC=com
     min_id = 1
```

### Steps to Reproduce:
change the attribute:  `default['sssd_ldap']['sssd_conf']['ldap_default_authtok']` and run chef client.  the new password is in the log. 

### Expected Result:
sensitive information should not be logged

**Comment by timw077** [comment]
@tas50 Can you look at this?  I submitted a simple fix. 

Thanks,
TimW

**Comment by tas50** [comment]
Closing this this has been merged
