### ISSUE TITLE
Version 4.2.1 is not available via the supermarket

### ISSUE THREAD

**Issue by rbogdany** [chef-cookbooks/sssd_ldap#34]
### Cookbook version
4.2.1

### Chef-client version
13.6.4

### Platform Details
RHEL7

### Scenario:
I would like to download version 4.2.1 from the supermarket but it is not available.

### Steps to Reproduce:
knife supermarket show sssd_ldap

### Expected Result:
I expect that to see 4.2.1 as an available version.

### Actual Result:
Version 4.2.0 is the latest I see.

**Comment by tas50** [comment]
Pushed to Supermarket. Thanks for the note
